# Generated by Django 3.2.4 on 2024-07-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(),
        ),
    ]
