# Generated by Django 3.2.4 on 2024-07-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20240723_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='preparation',
            field=models.TextField(default=''),
        ),
    ]
